# Generated by Django 4.2.6 on 2023-10-17 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
        ('livro', '0008_remove_livros_data_devolucao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='nome_emprestado_anonimo',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='nome_emprestado',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.DO_NOTHING, to='usuario.usuario'),
            preserve_default=False,
        ),
    ]
