# Generated by Django 4.2.6 on 2023-10-17 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0010_alter_emprestimo_nome_emprestado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emprestimo',
            name='tempo_duracao',
        ),
    ]
