# Generated by Django 4.2.6 on 2023-10-21 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0011_remove_emprestimo_tempo_duracao'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='avaliacao',
            field=models.CharField(choices=[('P', 'Péssimo'), ('R', 'Ruim'), ('B', 'Bom'), ('O', 'Ótimo')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
